<!-- Home page -->

<div class="container">
  <h3>My slills in Web-Developpement :</h3>
  <ul class="flex-list">
    <li>
      <div class="tooltip">
        <svg width="100" height="100">
          <circle cx="50" cy="50" r="40" stroke="#e34c26" stroke-width="4" fill="none" />
        </svg>
        <div class="box-tooltip">
          <div class="tooltip-text">
            HTML
          </div>
        </div>
      </div>
    </li>
    <li>
      <div class="tooltip">
        <svg width="100" height="100">
          <circle cx="50" cy="50" r="40" stroke="#0070BB" stroke-width="4" fill="none" />
        </svg>
        <div class="box-tooltip">
          <div class="tooltip-text">
            CSS
          </div>
        </div>
      </div>
    </li>
    <li>
      <div class="tooltip">
        <svg width="100" height="100">
          <circle cx="50" cy="50" r="40" stroke="#f0db4f" stroke-width="4" fill="none" />
        </svg>
        <div class="box-tooltip">
          <div class="tooltip-text">
            JS
          </div>
        </div>
      </div>
    </li>
    <li>
      <div class="tooltip">
        <svg width="100" height="100">
          <circle cx="50" cy="50" r="40" stroke="#8993be" stroke-width="4" fill="none" />
        </svg>
        <div class="box-tooltip">
          <div class="tooltip-text">
            PHP
          </div>
        </div>
      </div>
    </li>
    <li>
      <div class="tooltip">
        <svg width="100" height="100">
          <circle cx="50" cy="50" r="40" stroke="#00758F" stroke-width="4" fill="none" />
        </svg>
        <div class="box-tooltip">
          <div class="tooltip-text">
            MySQL
          </div>
        </div>
      </div>
    </li>
  </ul>
</div>
