<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width"/>
    <link rel="icon" type="image/png" href="<?= $wwwUrl ?>/images/logo-fox-150x150.png" />
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize.css">
    <link href="https://fonts.googleapis.com/css?family=Cuprum|Lobster" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

    <!-- Feuilles de styles de l'application -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/flexslider.css">

    <!-- Librairie jQuery -->
    <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>

    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>

    <title>Anastasiya Baryash</title>
  </head>
  <body>
  <!-- ------------------------------ HEADER ----------------------------- -->
      <header class="flex-header">
        <div class="img-transform">
          <a href="<?= $requestUrl ?>"><img src="<?= $wwwUrl ?>/images/logo-fox.png" alt="logo"></a>
        </div>
        <a class="h-transform" href="<?= $requestUrl ?>">
          <h1>Anastasiya Baryash</h1>
          <h2>Web-Developer</h2>
        </a>
        <nav>
          <ol class="list-transform">
            <li><a class="child1" href="#"><i class="fas fa-id-card child1"></i>Who I Am</a></li>
            <li><a class="child2" href="#"><i class="fas fa-folder-open child2"></i>My Projects</a></li>
            <li><a class="child3" href="#"><i class="fas fa-envelope child3"></i>Contact Me</a></li>
          </ol>
        </nav>
      </header>
  <!-- ------------------------------ MAIN ----------------------------- -->
      <main>
          <!-- Affichage du template lié à la vue -->
          <?php include $this->viewData['template'] ?>
      </main>
<!-- ------------------------------ FOOTER ----------------------------- -->
      <footer>
        <p>
          Follow me in:
        </p>
        <div class="flex-footer">
          <div class="icon-transform">
            <a href="https://www.linkedin.com/in/stasiyab/"><i class="fab fa-linkedin"></i></a>
          </div>
          <div class="icon-transform">
            <a href="#"><i class="fab fa-instagram"></i></a>
          </div>
          <div class="icon-transform">
            <a href="https://github.com/StasiyaB"><i class="fab fa-github-square"></i></a>
          </div>
        </div>
        <p>
          © StasiyaB, 2019
        </p>
      </footer>

<!-- Code principal JavaScript de l'application -->
  <script src="<?= $wwwUrl ?>/js/main.js"></script>

  </body>
</html>
