<div class="container">

    <div class="flexslider">
      <ul class="slides">
        <li>
          <img src="<?= $wwwUrl ?>/images/slider/01-Cup-of-Tea.png" />
        </li>
        <li>
          <img src="<?= $wwwUrl ?>/images/slider/02-Wolf-Gang.png" />
        </li>
        <li>
          <img src="<?= $wwwUrl ?>/images/slider/03-Carrousel.png" />
        </li>
      </ul>
    </div>



</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
<script src="<?= $wwwUrl ?>/js/jquery.flexslider.js"></script>
<script type="text/javascript" charset="utf-8">
  $(window).load(function() {
    $('.flexslider').flexslider();
  });
</script>
