<div class="container">
  <h2><i class="fas fa-user-cog"></i> Administration log by : <span><?= $_SESSION['Name'] ?></span></h2>

  <form action="<?= $requestUrl ?>/admin/location/" enctype="multipart/form-data" method="POST">

    <fieldset>
      <legend>Add new project</legend>

      <div class="form-flex">
        <input id="Name" type="text" name="ProjectName" value="" placeholder="Project Name">
        <input id="Image" type="file" name="Image" value="" size="30" placeholder="Progect Image">
        <input id="Techno" type="text" name="TechnologyUsed" value="" placeholder="Technology Used">
        <input id="URL" type="text" name="URL" value="" placeholder="URL of the Project">
        <textarea id="Description" name="ProjectDescription" placeholder="Project Description" rows="3"></textarea>
      </div>

      <div class="button">
        <button id="send" type="submit">Send</button>
        <button id="deleteForm">Delete</button>
      </div>

    </fieldset>
  </form>

  <nav class="flex-nav">
    <a class="login" href="<?= $requestUrl ?>/admin/login/">Add User</a>
    <a class="logout" href="<?= $requestUrl ?>/admin/logout/">Logout</a>
  </nav>

  <table>
    <caption><span>Projects list</span></caption>

    <thead>
      <th>Image</th>
      <th>Project name</th>
      <th>Project description</th>
      <th>Technology used</th>
      <th>URL</th>
    </thead>

    <tbody>
      <?php foreach ($projects as $project) { ?>
        <tr>
          <td>
            <img src="<?= $wwwUrl ?>/images/upload/<?=$project['Image']?>" alt="<?=$project['ProjectName']?>">
          </td>
          <td>
            <?=$project['ProjectName']?>
          </td>
          <td>
            <?=$project['ProjectDescription']?>
          </td>
          <td>
            <?=$project['TechnologyUsed']?>
          </td>
          <td>
            <?=$project['URL']?>
          </td>
        </tr>
      <?php } ?>
    </tbody>
  </table>
</div>
<script type="text/javascript" src="<?= $wwwUrl ?>/js/classes/ProjectSession.class.js"></script>
