<div class="container">
  <section>
    <article>
      <h3>Who I am</h3>
      <div class="id">
        <img src="<?= $wwwUrl ?>/images/img-logo.png" alt="Photo">
      </div>
      <div class="about">
        <p>My name is Anastasiya. I'm a web developer. Now I live in the suburb of Paris, France, but I was born in Minsk, Belarus. I speak Russian, English and French languages.</p>
        <p>I’ve just terminated my studies in <span><a href="https://3wa.fr/" target="_blank">“3W Academy”</a></span> where I’ve learned <span><a href="<?= $requestUrl ?>/"> 5 general WEB technologies</a></span> and passed 90% of educational time, creating <span><a href="<?= $requestUrl ?>/project/">projects in practice</a></span>. My love to keep everything under control and in order helps me a lot in my work. It’s a great pleasure to see how the lines of code that I'm creating transforms in visual effects, design or  an action.</p>
        <p>I adore to interpret my desires through the code. As well I’m fun of music, dogs and a good reading.</p>
        <br>
        <p>Think we could create something together? Feel free to <span><a href="<?= $requestUrl ?>/contact/">drop me an email</a></span>.</p>
        <p>For a closer look to my working experience and skills, please, <span><a href="<?= $wwwUrl ?>/id/pdf/CV_BaryashA.pdf" target="_blank">download or print my CV</a></span>.
        </p>
        <br>
        <p>  Thanks for visiting my page! <span>; )</span></p>
      </div>
    </article>
  </section>
</div>
