<div class="container">
  <form action="<?= $requestUrl ?>/contact/" method="POST">
    <fieldset>
      <legend>Contact me</legend>

      <div class="form-flex">
        <input id="Name" type="text" name="Name" value="" placeholder="Your name">
        <input id="Mail" type="text" name="Mail" value="" placeholder="Your mail*" required>
        <input id="Subject" type="text" name="Subject" value="" placeholder="Subject">
        <textarea id="Message" name="Message" placeholder="Your message" rows="3"></textarea>
      </div>

      <div class="button">
        <button type="submit">Send</button>
        <button type="submit" id="deleteForm">Delete</button>
      </div>

    </fieldset>
  </form>
</div>
<script type="text/javascript" src="<?= $wwwUrl ?>/js/classes/ContactSession.class.js"></script>
